---
inherit_from:
  - .rubocop_airbnb.yml

Rails:
  Enabled: true

AllCops:
  Exclude:
    - spec/spec_helper.rb
    - spec/dummy/**/*
    - bin/*
    - vendor/bundle/**/*
    - db/**/*
    - config/**/*
    - Gemfile
